# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3638ef00075925dca06ea52ad8b17bc1e7185f607ecdceddae3caae5d3d2d4a1f65a24f6c9b6f09b8d6a64ee8d95764500e3f9033767e1c9472cb22ddbe3141d

test:
  secret_key_base: 650ab0dd553138182f386dbea68ce2a88b15f0979d41f1ea2bd629feeaf88e8d56625d0cef51e7d4545f479dd63024c45709080637bab40b2852b4e09b573612

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
